#!/usr/bin/env node

/**
 * Universal Dev Server Runner with Smart Fallback & First-Run Setup
 *
 * Generated by xport setup
 */

import { spawn, spawnSync } from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const projectRoot = path.resolve(__dirname, '..');

function ensureLocalEnv() {
  const envLocal = path.join(projectRoot, '.env.local');
  const envExample = path.join(projectRoot, '.env.example');

  if (!fs.existsSync(envLocal) && fs.existsSync(envExample)) {
    try {
      fs.copyFileSync(envExample, envLocal);
      console.log('\x1b[32m✔ [setup] Initialized .env.local from .env.example\x1b[0m');
      return true;
    } catch (err) {
      console.warn('⚠ [setup] Could not create .env.local:', err.message);
    }
  }
  return false;
}

ensureLocalEnv();

if (process.argv.includes('--setup-only')) {
  process.exit(0);
}

const args = process.argv.slice(2).filter((arg) => arg !== '--setup-only' && arg !== '--');
const defaultCommand = args.length > 0 ? args : ['next', 'dev'];

function getBinPaths(startDir) {
  const bins = [];
  let curr = startDir;
  while (curr) {
    const candidate = path.join(curr, 'node_modules', '.bin');
    if (fs.existsSync(candidate)) {
      bins.push(candidate);
    }
    const parent = path.dirname(curr);
    if (parent === curr) break;
    curr = parent;
  }
  return bins;
}

const extraPaths = getBinPaths(projectRoot);
const pathEnv = process.env.PATH || '';
const env = {
  ...process.env,
  PATH: extraPaths.length > 0
    ? `${extraPaths.join(path.delimiter)}${path.delimiter}${pathEnv}`
    : pathEnv,
};

function hasXportCli() {
  try {
    const res = spawnSync('xport', ['--version'], {
      stdio: 'ignore',
      shell: true,
      windowsHide: true,
    });
    return res.status === 0;
  } catch {
    return false;
  }
}

const hasXport = hasXportCli();

function runDirect(cmdArgs) {
  const [bin, ...rest] = cmdArgs;
  const child = spawn(bin, rest, {
    cwd: projectRoot,
    env,
    stdio: 'inherit',
    shell: true,
  });

  child.on('exit', (code, signal) => {
    if (signal) process.kill(process.pid, signal);
    else process.exit(code ?? 0);
  });

  process.on('SIGINT', () => child.kill('SIGINT'));
  process.on('SIGTERM', () => child.kill('SIGTERM'));
}

if (hasXport) {
  const child = spawn('xport', ['run', ...defaultCommand], {
    cwd: projectRoot,
    env,
    stdio: 'inherit',
    shell: true,
  });

  let childStarted = false;
  child.on('spawn', () => { childStarted = true; });

  child.on('error', (err) => {
    console.warn(`[dev] xport run failed (${err.message}), falling back to direct run...`);
    runDirect(defaultCommand);
  });

  child.on('exit', (code, signal) => {
    if (signal) {
      process.kill(process.pid, signal);
    } else if (code !== 0 && !childStarted) {
      console.warn(`[dev] xport exited with code ${code}, falling back to direct dev server...`);
      runDirect(defaultCommand);
    } else {
      process.exit(code ?? 0);
    }
  });

  process.on('SIGINT', () => child.kill('SIGINT'));
  process.on('SIGTERM', () => child.kill('SIGTERM'));
} else {
  runDirect(defaultCommand);
}
